baseURL = "https://nunor1001.github.io/myblog/"
languageCode = 'en-us'
title = 'Nunor의 인식'
theme = "PaperMod"
buildDrafts = false
buildFuture = false

enableRobotsTXT = true
enableGitInfo = true         # 마지막 수정일 자동 반영용

[pagination]
  pagerSize = 12

# 태그/카테고리 활성화
[taxonomies]
  category = "categories"
  tag = "tags"

# 홈(검색용 JSON 포함)
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  defaultTheme = "dark"          # 다크 기본
  ShowReadingTime = true         # 읽는 시간
  ShowPostNavLinks = true        # 이전/다음 글
  ShowBreadCrumbs = true         # 빵부스러기
  ShowCodeCopyButtons = true     # 코드 복사 버튼
  ShowToc = true                 # 글 내 목차
  TocOpen = false
  ShowLastMod = true             # 마지막 수정일 표기
  comments = false               # 필요하면 true + 시스템 설정
  # 홈 히어로(optional)
  homeInfoParams = { Title = "Data, calmly observed.", Content = "데이터로 사회를 해석하는 저널" }

  # 소셜 아이콘(필요한 것만)
  [[params.socialIcons]]
    name = "github"
    url  = "https://github.com/Nunor1001"

# 관련 글(태그/카테고리 기반 추천)
[related]
  threshold = 0
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 80

# 상단 매뉴
[minify]
  minifyOutput = true

[[menu.main]]
  name = "Posts"
  url  = "/posts/"
  weight = 10

[[menu.main]]
  name = "About"
  url  = "/about/"
  weight = 20

[[menu.main]]
  name = "Search"
  url  = "/search/"
  weight = 30
